stages:
  ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
    - src/data/data_ingestion.py
    outs:
    - data/raw_data/current.csv
    - data/raw_data/reference.csv

  splitting:
    cmd: python src/data/split_data.py
    deps:
    - data/raw_data/current.csv
    - src/data/split_data.py
    outs:
    - data/split_data/X_test.csv
    - data/split_data/X_train.csv
    - data/split_data/y_test.csv
    - data/split_data/y_train.csv

  normalize_data:
    cmd: python src/data/normalize_data.py
    deps:
    - data/split_data
    - src/data/normalize_data.py
    outs:
    - data/normalized_data/X_test_scaled.csv
    - data/normalized_data/X_train_scaled.csv
    - data/normalized_data/y_test.csv
    - data/normalized_data/y_train.csv

  grid_search:
    cmd: python src/models/grid_search.py
    deps:
    - data/normalized_data/X_test_scaled.csv
    - data/normalized_data/X_train_scaled.csv
    - data/normalized_data/y_test.csv
    - data/normalized_data/y_train.csv
    - src/models/grid_search.py
    outs:
    - models/best_parameters/best_params.pkl

  train_model:
    cmd: python src/models/train_model.py
    deps:
    - data/normalized_data/X_test_scaled.csv
    - data/normalized_data/X_train_scaled.csv
    - data/normalized_data/y_test.csv
    - data/normalized_data/y_train.csv
    - models/best_parameters/best_params.pkl
    - src/models/train_model.py
    outs:
    - models/saved_models/trained_model.pkl

  evaluate_model:
    cmd: python src/models/evaluate_model.py
    deps:
    - data/normalized_data/X_test_scaled.csv
    - data/normalized_data/y_test.csv
    - models/saved_models/trained_model.pkl
    - src/models/evaluate_model.py
    outs:
    - metrics/predictions.csv
    - metrics/scores.json
  data_drift:
    cmd: python src/data/drift_monitoring.py
    deps:
    - data/normalized_data/X_test_scaled.csv
    - data/normalized_data/y_test.csv
    - src/data/drift_monitoring.py
    outs:
    - metrics/data_drift.json
    - reports/data_drift.html
