stages:
  ingestion:
    cmd: python src/data/ingestion.py
    deps:
      - src/data/ingestion.py
    outs:
      - data/raw_data/current.csv
      - data/raw_data/reference.csv
  
  drift_monitoring:
    cmd: python src/data/drift_monitoring.py
    deps:
      - data/raw_data/current.csv
      - data/raw_data/reference.csv
      - src/data/drift_monitoring.py
    outs:
      - metrics/data_drift.json
      - reports/data_drift.html

  performance_drift_monitoring:
    cmd: python src/data/performance_drift_monitoring.py
    deps:
      - data/raw_data/current.csv
      - data/raw_data/reference.csv
      - src/data/performance_drift_monitoring.py
      - preprocessing/scalers/Humidity3pm_scaler.pkl
      - preprocessing/scalers/Humidity9am_scaler.pkl
      - preprocessing/scalers/MaxTemp_scaler.pkl
      - preprocessing/scalers/MinTemp_scaler.pkl
      - preprocessing/scalers/Pressure3pm_scaler.pkl
      - preprocessing/scalers/Pressure9am_scaler.pkl
      - preprocessing/scalers/Rainfall_scaler.pkl
      - preprocessing/scalers/Temp3pm_scaler.pkl
      - preprocessing/scalers/Temp9am_scaler.pkl
      - preprocessing/scalers/WindGustSpeed_scaler.pkl
      - preprocessing/scalers/WindSpeed3pm_scaler.pkl
      - preprocessing/scalers/WindSpeed9am_scaler.pkl
      - preprocessing/label_encoders/Location_le.pkl
      - preprocessing/label_encoders/WindDir3pm_le.pkl
      - preprocessing/label_encoders/WindDir9am_le.pkl
      - preprocessing/label_encoders/WindGustDir_le.pkl
      - models/best_parameters/best_params.pkl
      - src/models/train_model.py
    outs:
      - metrics/

  splitting:
    cmd: python src/data/split_data.py
    deps: 
      - data/raw_data/current.csv
      - src/data/split_data.py
    outs:
      - data/split_data/X_test.csv
      - data/split_data/X_train.csv
      - data/split_data/y_test.csv
      - data/split_data/y_train.csv

  normalize_data:
    cmd: python src/data/normalize_data.py
    deps:
      - data/split_data
      - src/data/normalize_data.py
    outs:
      - data/normalized_data/X_test_scaled.csv
      - data/normalized_data/X_train_scaled.csv
      - data/normalized_data/y_test.csv
      - data/normalized_data/y_train.csv
      - preprocessing/scalers/Humidity3pm_scaler.pkl
      - preprocessing/scalers/Humidity9am_scaler.pkl
      - preprocessing/scalers/MaxTemp_scaler.pkl
      - preprocessing/scalers/MinTemp_scaler.pkl
      - preprocessing/scalers/Pressure3pm_scaler.pkl
      - preprocessing/scalers/Pressure9am_scaler.pkl
      - preprocessing/scalers/Rainfall_scaler.pkl
      - preprocessing/scalers/Temp3pm_scaler.pkl
      - preprocessing/scalers/Temp9am_scaler.pkl
      - preprocessing/scalers/WindGustSpeed_scaler.pkl
      - preprocessing/scalers/WindSpeed3pm_scaler.pkl
      - preprocessing/scalers/WindSpeed9am_scaler.pkl
      - preprocessing/label_encoders/Location_le.pkl
      - preprocessing/label_encoders/WindDir3pm_le.pkl
      - preprocessing/label_encoders/WindDir9am_le.pkl
      - preprocessing/label_encoders/WindGustDir_le.pkl

  grid_search:
    cmd: python src/models/grid_search.py
    deps:
      - data/normalized_data/X_test_scaled.csv
      - data/normalized_data/X_train_scaled.csv
      - data/normalized_data/y_test.csv
      - data/normalized_data/y_train.csv
      - src/models/grid_search.py
    outs:
      - models/best_parameters/best_params.pkl

  train_model:
    cmd: python src/models/train_model.py
    deps:
      - data/normalized_data/X_test_scaled.csv
      - data/normalized_data/X_train_scaled.csv
      - data/normalized_data/y_test.csv
      - data/normalized_data/y_train.csv
      - models/best_parameters/best_params.pkl
      - src/models/train_model.py
    outs:
      - models/saved_models/trained_model.pkl

  evaluate_model:
    cmd: python src/models/evaluate_model.py
    deps:
      - data/normalized_data/X_test_scaled.csv
      - data/normalized_data/y_test.csv
      - models/saved_models/trained_model.pkl
      - src/models/evaluate_model.py
    outs:
      - metrics/predictions.csv
      - metrics/scores.json
