global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'airflow'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['172.20.79.133:8000']  # Replace with your IP address
  - job_name: 'data_drift_metrics'
    static_configs:
      - targets: ['172.20.79.133:8000']
  - job_name: 'performance_metrics'
    static_configs:
      - targets: ['172.20.79.133:8000']

